# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93a608b1be2e1439bdebd8382dcbdd99757db3806c4f834e143866e6a9fd74b5e23bcf0ab6e378b344c8beff470d76a657badea067639deaa84f9ee1d2ba9252

test:
  secret_key_base: 2db1244dc5f76b96adf866916f677ec38cbb409e33383388fcaed56966f66ded91186b75be58593a08971b421ed6c7ffe98fa1b14f3011011364c77740f3ba3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
